### ISSUE TITLE
@http variable is nil in Mechanize

### ISSUE THREAD

**Issue by ghedsouza** [mcmire/address_standardization#9]
I'm getting an error when trying to use the MelissaData service:

I traced it back a bit, and it's happening due to @http being nil in Mechanize::HTTP::Agent, but I haven't looked any further.

```
ruby-1.9.2-p180 :001 > require 'address_standardization'
 => true 
ruby-1.9.2-p180 :002 > AddressStandardization::MelissaData.standardize_address(:city => "New York")
NoMethodError: undefined method `request' for nil:NilClass
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/mechanize-2.0.1/lib/mechanize/http/agent.rb:204:in `fetch'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/mechanize-2.0.1/lib/mechanize.rb:386:in `get'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/address_standardization-0.4.1/lib/address_standardization/melissa_data.rb:27:in `block in get_live_response'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/mechanize-2.0.1/lib/mechanize.rb:312:in `initialize'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/address_standardization-0.4.1/lib/address_standardization/melissa_data.rb:25:in `new'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/address_standardization-0.4.1/lib/address_standardization/melissa_data.rb:25:in `get_live_response'
    from /Users/ed/.rvm/gems/ruby-1.9.2-p180@gaggleup/gems/address_standardization-0.4.1/lib/address_standardization/abstract_service.rb:12:in `standardize_address'
    from (irb):2
    from /Users/ed/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in `<main>'
ruby-1.9.2-p180 :003 > ^D
```

**Comment by mcmire** [comment]
Okay. I'll try to look at this later today.

**Comment by mcmire** [comment]
Okay, I looked into this and I believe this may be an issue with Mechanize. The latest version is 2.0.1; when I roll back to 2.0.0 then I don't get that error. Now, 2.0.1 was released in June and there has been ongoing work on Mechanize since then, including the file where the exception is being raised, as you can see [here](https://github.com/tenderlove/mechanize/commits/master/lib/mechanize/http/agent.rb). So it is possible that the issue has been fixed already -- I'm not sure.

In any case, I plan on releasing a new version of this gem soon which will hardcode the dependency on Mechanize to 2.0.0.

**Comment by mcmire** [comment]
Okay, I have my latest changes on master. Would you try it out really quickly in your app/library? (You can add a :git dependency using Bundler; or if you are not using Bundler, download the source, `gem build *.gemspec`, and then `gem install *.gem`.) If all works well then I will push out a new version.

**Comment by mcmire** [comment]
I have pushed v0.4.2.rc1 so you can quickly test this out without having to build the gem yourself. You can install this with `gem install address_standardization --pre`.
